import type { ThemeModel } from '@theme';

const TEXT_VARIANTS: ThemeModel['textVariants'] = {
    defaults: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 17,
        lineHeight: 22,
        letterSpacing: -0.408,
        color: 'text_primary',
    },
    headline_1_bold: {
        fontFamily: 'Inter_700Bold',
        fontWeight: '700',
        fontSize: 40,
        lineHeight: 48,
        letterSpacing: 0.41,
    },
    headline_1: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 40,
        lineHeight: 48,
        letterSpacing: 0.41,
    },
    large_title_bold: {
        fontFamily: 'Inter_700Bold',
        fontWeight: '700',
        fontSize: 34,
        lineHeight: 41,
        letterSpacing: 0.374,
    },
    large_title: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 34,
        lineHeight: 41,
        letterSpacing: 0.374,
    },
    title_1_bold: {
        fontFamily: 'Inter_700Bold',
        fontWeight: '700',
        fontSize: 28,
        lineHeight: 34,
        letterSpacing: 0.364,
    },
    title_1: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 28,
        lineHeight: 34,
        letterSpacing: 0.364,
    },
    title_2_bold: {
        fontFamily: 'Inter_700Bold',
        fontWeight: '700',
        fontSize: 22,
        lineHeight: 28,
        letterSpacing: 0.35,
    },
    title_2: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 22,
        lineHeight: 28,
        letterSpacing: 0.35,
    },
    title_3_bold: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 20,
        lineHeight: 25,
        letterSpacing: 0.38,
    },
    title_3: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 20,
        lineHeight: 25,
        letterSpacing: 0.38,
    },
    headline_bold: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 17,
        lineHeight: 22,
        letterSpacing: -0.408,
    },
    headline: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 17,
        lineHeight: 22,
        letterSpacing: -0.408,
    },
    body_20_bold: {
        fontFamily: 'Inter_700Bold',
        fontWeight: '700',
        fontSize: 20,
        lineHeight: 25,
        letterSpacing: 0.38,
    },
    body_20: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 20,
        lineHeight: 25,
        letterSpacing: 0.38,
    },
    body_bold: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 17,
        lineHeight: 22,
        letterSpacing: -0.408,
    },
    body: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 17,
        lineHeight: 22,
        letterSpacing: -0.408,
    },
    callout_bold: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 16,
        lineHeight: 21,
        letterSpacing: -0.32,
    },
    callout: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 16,
        lineHeight: 21,
        letterSpacing: -0.32,
    },
    subheadline_bold: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 15,
        lineHeight: 20,
        letterSpacing: -0.5,
    },
    subheadline: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 15,
        lineHeight: 20,
        letterSpacing: -0.24,
    },
    footnote_bold: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 13,
        lineHeight: 18,
        letterSpacing: -0.078,
    },
    footnote: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 13,
        lineHeight: 18,
        letterSpacing: -0.078,
    },
    caption_1_bold: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0,
    },
    caption_1: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0,
    },
    caption_2_bold: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 11,
        lineHeight: 13,
        letterSpacing: 0.066,
    },
    caption_2: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 11,
        lineHeight: 13,
        letterSpacing: 0.066,
    },
    caption_3_bold: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 10,
        lineHeight: 12,
        letterSpacing: 0.07,
    },
    caption_3: {
        fontFamily: 'Inter_500Medium',
        fontWeight: '500',
        fontSize: 10,
        lineHeight: 12,
        letterSpacing: 0.07,
    },
    button: {
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
        fontSize: 17,
        lineHeight: 22,
        letterSpacing: 0.38,
    },
    button_ghost: {
        fontFamily: 'Inter_500Medium',
        fontWeight: '500',
        fontSize: 17,
        lineHeight: 22,
        letterSpacing: 0.38,
        paddingVertical: 's',
    },
    header_button: {
        fontFamily: 'Inter_500Medium',
        fontWeight: '500',
        fontSize: 17,
        lineHeight: 20,
        letterSpacing: 0.38,
    },
    link: {
        fontFamily: 'Inter_400Regular',
        fontWeight: '400',
        fontSize: 12,
        letterSpacing: 0.38,
        lineHeight: 16,
        color: 'emphasis',
        textDecorationLine: 'underline',
    },
    label: {
        fontFamily: 'Inter_500Medium',
        fontWeight: '500',
        fontSize: 13,
        lineHeight: 18,
        letterSpacing: 0.38,
    },
};

export { TEXT_VARIANTS };
